# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Author'),
        ),
    ]
