# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20171129_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
