# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_remove_text_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='author',
        ),
        migrations.AddField(
            model_name='authorship',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Text'),
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='corpus.Authorship', to='corpus.Text'),
        ),
    ]
